"""add external_id, region, fz_sub_id to positions

Revision ID: 06320496cc6d
Revises: 989bd463c90f
Create Date: 2026-09-20 19:33:44.898779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06320496cc6d'
down_revision: Union[str, None] = '989bd463c90f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('external_id', sa.String(length=300), nullable=False))
    op.add_column('positions', sa.Column('fz_sub_id', sa.Integer(), nullable=True))
    op.add_column('positions', sa.Column('region', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_positions_external_id'), 'positions', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positions_external_id'), table_name='positions')
    op.drop_column('positions', 'region')
    op.drop_column('positions', 'fz_sub_id')
    op.drop_column('positions', 'external_id')
    # ### end Alembic commands ###
