"""position fz availability dates

Revision ID: 1a9cd2e2943d
Revises: 89f36cfe87f1
Create Date: 2026-10-01 18:26:17.049346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a9cd2e2943d'
down_revision: Union[str, None] = '89f36cfe87f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('fz_missing_since', sa.DateTime(timezone=True), nullable=True))
    op.add_column('positions', sa.Column('fz_out_of_stock_since', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'fz_out_of_stock_since')
    op.drop_column('positions', 'fz_missing_since')
    # ### end Alembic commands ###
