"""add variant_label to positions

Revision ID: 448c72f30a1c
Revises: 4eb3dfb481e5
Create Date: 2026-10-01 16:51:32.524620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '448c72f30a1c'
down_revision: Union[str, None] = '4eb3dfb481e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('variant_label', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'variant_label')
    # ### end Alembic commands ###
