"""add ggsell category and fees to listings

Revision ID: 4eb3dfb481e5
Revises: 06320496cc6d
Create Date: 2026-09-30 03:31:59.884730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb3dfb481e5'
down_revision: Union[str, None] = '06320496cc6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('ggsell_category_id', sa.Integer(), nullable=True))
    op.add_column('listings', sa.Column('ggsell_fee', sa.Numeric(precision=6, scale=4), server_default='0', nullable=False))
    op.add_column('listings', sa.Column('ggsell_payment_fee', sa.Numeric(precision=6, scale=4), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'ggsell_payment_fee')
    op.drop_column('listings', 'ggsell_fee')
    op.drop_column('listings', 'ggsell_category_id')
    # ### end Alembic commands ###
