"""order fz status and seller payout

Revision ID: 89f36cfe87f1
Revises: 9658f9bb8c53
Create Date: 2026-10-01 18:02:12.647583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89f36cfe87f1'
down_revision: Union[str, None] = '9658f9bb8c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('fz_status', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('fz_ordered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('seller_payout_rub', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'seller_payout_rub')
    op.drop_column('orders', 'fz_ordered_at')
    op.drop_column('orders', 'fz_status')
    # ### end Alembic commands ###
