"""add options_attached to listings

Revision ID: 9658f9bb8c53
Revises: 95af5bb5d065
Create Date: 2026-10-01 17:27:50.366010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9658f9bb8c53'
down_revision: Union[str, None] = '95af5bb5d065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('options_attached', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'options_attached')
    # ### end Alembic commands ###
