"""init positions, listings, orders

Revision ID: 989bd463c90f
Revises: 
Create Date: 2026-09-20 19:11:59.418285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '989bd463c90f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('fz_category_id', sa.String(length=100), nullable=True),
    sa.Column('fz_offer_id', sa.String(length=100), nullable=True),
    sa.Column('fz_appid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('last_known_price_usd', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('ggsell_offer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('price_rub', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_source_usd_at_sync', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_ggsell_offer_id'), 'listings', ['ggsell_offer_id'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ggsell_invoice_id', sa.String(length=100), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('buyer_data', sa.JSON(), nullable=False),
    sa.Column('price_at_sale_rub', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_deviation_percent', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fz_order_id', sa.String(length=100), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('delivered_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_ggsell_invoice_id'), 'orders', ['ggsell_invoice_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_ggsell_invoice_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_listings_ggsell_offer_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_table('positions')
    # ### end Alembic commands ###
