"""stage 7 unit price precision order quantity

Revision ID: 9fd28d8963b9
Revises: 1a9cd2e2943d
Create Date: 2026-10-05 21:44:24.890663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd28d8963b9'
down_revision: Union[str, None] = '1a9cd2e2943d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'price_source_usd_at_sync',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=16, scale=8),
               existing_nullable=False)
    op.add_column('orders', sa.Column('quantity', sa.Integer(), server_default='1', nullable=False))
    op.alter_column('positions', 'last_known_price_usd',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=16, scale=8),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('positions', 'last_known_price_usd',
               existing_type=sa.Numeric(precision=16, scale=8),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=False)
    op.drop_column('orders', 'quantity')
    op.alter_column('listings', 'price_source_usd_at_sync',
               existing_type=sa.Numeric(precision=16, scale=8),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###
